### ISSUE TITLE
No such file or directory: './creds.json'

### ISSUE THREAD

**Issue by blackary** [mwhitaker/dbt-action#19]
I have the following step 
```yaml
- name: dbt-run
  uses: mwhitaker/dbt-action@fishtown-v0.19.1
  with:
    dbt_command: "dbt run --profiles-dir ."
  env:
    DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
```

And I have a profiles.yml in the directory, and a secret value set in the repository. But, when that step runs, I get 
```
ERROR: Database Error
  [Errno 2] No such file or directory: './creds.json'
```

I thought that the creds.json file would be automatically created for me, so I'm unsure why it's failing.

**Comment by mwhitaker** [comment]
Hi there,

I am not sure to be honest. I just [ran a workflow](https://github.com/mwhitaker/dbt-action-sample/actions/runs/1785369716) with that same image with no issue. Can you share your whole workflow file and or workflow run?

Michael

**Comment by blackary** [comment]
Here's my entire workflow 
```yaml
name: Run dbt build and test on push

on:
  push:
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        uses: mwhitaker/dbt-action@fishtown-v0.19.1
        with:
          dbt_command: "dbt deps --profiles-dir ."
        env:
          DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
      - name: dbt-run
        uses: mwhitaker/dbt-action@fishtown-v0.19.1
        with:
          dbt_command: "dbt run --profiles-dir ."
        env:
          DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
      - name: dbt-test
        uses: mwhitaker/dbt-action@fishtown-v0.19.1
        with:
          dbt_command: "dbt test --profile-dir ."
        env:
          DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
```

The first one succeeds, but the second one fails with that error.

**Comment by mwhitaker** [comment]
Let's try to move the env to the top level since it's repeated anyway:

```yml
name: Run dbt build and test on push

on:
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: .
  DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        uses: mwhitaker/dbt-action@fishtown-v0.19.1
        with:
          dbt_command: "dbt deps"
          dbt_project_folder: "dbt_project"
      - name: dbt-run
        uses: mwhitaker/dbt-action@fishtown-v0.19.1
        with:
          dbt_command: "dbt run"
          dbt_project_folder: "dbt_project"
      - name: dbt-test
        uses: mwhitaker/dbt-action@fishtown-v0.19.1
        with:
          dbt_command: "dbt test"
          dbt_project_folder: "dbt_project"
```

For me this runs in my test repo. [See here](https://github.com/mwhitaker/dbt-action-sample/actions/runs/1786843580). Note that the test step fails for normal reasons because one of the tests fails, but there is no issue with the credentials file.

If that still doesn't work for you, I suspect that the issue somehow is about your folder structure and where your `profiles.yml` file is located in relation to the dbt project files.
