### ISSUE TITLE
Run several dbt commands

### ISSUE THREAD

**Issue by halvorlu** [mwhitaker/dbt-action#26]
Thanks for a useful action.
I haven't figured out how to run several dbt commands in series, such as `dbt deps` followed by `dbt build`. Is this possible with the current code?

**Comment by mwhitaker** [comment]
Hi there,

Something like this should work:

```yml
 steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt deps"
          dbt_project_folder: "dbt_project"
      - name: dbt-run
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt run"
          dbt_project_folder: "dbt_project"
      - name: dbt-test
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt test"
          dbt_project_folder: "dbt_project"
```
The image will only be downloaded and built once.
Let me know if that works for you.

Michael
