### ISSUE TITLE
Password exposed in logs

### ISSUE THREAD

**Issue by simon-tarr** [mwhitaker/dbt-action#29]
Got a weird one here. I'm using the [latest commit](https://github.com/mwhitaker/dbt-action/commit/56f1f21c8026df783c17f65743b17855b5be22d9) to master in my Github Action. I have a password which includes two '&' (ampersand) but I get the error:

```
trying to use user/password
saving console output in "./dbt_console_output.txt"
15:28:26  Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  Runtime Error
    Syntax error near line 9
    ------------------------------
    6  |       type: snowflake
    7  |       account:
    8  |       user: ***
    9  |       password: *SOMEOFMYPASSWORD_password_SOMEOFMYPASSWORD_password_***
    10 |       role: ANALYST
    [11](https://github.com...) |       database: FOO
    [12](https://github.com...) |       warehouse: BAR
    
    Raw Error:
    ------------------------------
    while scanning an alias
      in "<unicode string>", line 9, column [17](https://github.com...)
    did not find expected alphabetic or numeric character
      in "<unicode string>", line 9, column [18](https://github.com...)
```
Where I've written SOMEOFMYPASSWORD....well, the logs are actually _printing my password_ up to the amersands. Then it continues to print more of my password in plaintext until the second ampersand.

I have configured my password as per the Readme:

```
# profiles.yml
my_dataset:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: _user_      # this will be substituted during build time
      pass: _password_  # this will be substituted during build time
      port: 5432
      dbname: tutorial
      schema: dbt_tutorial
  target: dev
```
And added the required secrets to allow the action to parse the authentication details.

Presumably this isn't expected behaviour?
