### ISSUE TITLE
Parsing of _user_ and _password_ failing

### ISSUE THREAD

**Issue by extrobe** [mwhitaker/dbt-action#44]
Hi, I'm trying to set this up to work with Snowflake, but struggling to get the credentials passed to the profiles.yml file.

I've set up the profile with `_user_` and `_password_` , and created env vars in the workflow file, which map back to my stored secrets.

```yml
docs:
 account: <my_account>
 database: <my_db>
 user: _user_
 password: _password_
 role: <my_role>
 schema: dev
 threads: 2
 type: snowflake
 warehouse: <my_compute>
```

But this fails to authenticate. If I hard-code the credentials in the profiles file, it works fine. If I hard-code the environment variables (rather than grabbing from secrets) it _fails_ . But if I print the env_vars to console, they're there - so I think it's failing to map the environment variables to `_user_` and `_password_` .

Have I misunderstood how to configure this, or is this a bug?

My workflow step looks like this...

```yml
      - name: Generate DBT Docs
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt docs generate --profiles-dir ../docs_hosting/"
          dbt_project_folder: "dbt/dbtlearn"
        env:
          DBT_USER: ${{ secrets.SF_USER }}
          DBT_PASSWORD: ${{ secrets.SF_PWD }}
```

**Comment by mwhitaker** [comment]
I suspect that it has something to do with your folder structure and that the code can't find your profile.yml file to do the user/password substitution. Can you send me (either here or by [email](https://github.com/mwhitaker)) an outline of your folder structure, ie where the profile.yml and dbt models are.

**Comment by extrobe** [comment]
I'm fairly confident it's reading the profiles file OK, as the error message that comes off notes the Snowflake server I'm connecting to (which must be coming from the profiles file), and if I hard-code the values in the profiles file, it finds them & connects OK.

```
Database Error
  250001 (08001): Failed to connect to DB: <my_account>.snowflakecomputing.com:443. Incorrect username or password was specified.
```

folder structure per below...

```yml
- /dbt
 - /dbtlearn
  - /models
  - /seeds
  - dbt_project.yml
  - packages.yml
 - /docs_hosting
  - profiles.yml
  - staticwebapp.config.json
- /.github
 - /workflows
  - workflow.yml
```

**Comment by mwhitaker** [comment]
I see. Yeah, this action does assume that `profiles.yml` is at the root of your dbt project, so in `dbt/dbtlearn`. In that case you'd just use
```yaml
with:
   dbt_command: "dbt docs generate"
   dbt_project_folder: "dbt/dbtlearn"
```
If it's important to keep profiles.yml in a different folder that's possible of course. I have a test here in the **profdir** branch:

```yml
- name: Generate DBT Docs
  uses: mwhitaker/dbt-action@profdir
  with:
     dbt_command: "dbt docs generate"
     dbt_project_folder: "dbt/dbtlearn"
     dbt_profile_folder: "../docs_hosting"
  env:
     DBT_USER: ${{ secrets.SF_USER }}
     DBT_PASSWORD: ${{ secrets.SF_PWD }}
```
Give that a try and let me if it's important to have going forward.
