### ISSUE TITLE
dbt project not found

### ISSUE THREAD

**Issue by leo-schick** [mwhitaker/dbt-action#45]
I have a strange error with the dbt action:

I wanted to set up dbt-action to just validate the source code so I set up the workflow like this:

``` yml
name: CI

on:
  push:
    branches:
      - main
      - stage
      - prod

jobs:
  build:
    name: Parse project
    runs-on: ubuntu-latest
    steps:
      - name: dbt action
        uses: mwhitaker/dbt-action@v1.3.0
        with:
          dbt_command: dbt parse
```

But it fails with that it cannot find the `dbt_project.yml` file:

![image](https://user-images.githubusercontent.com/67712864/214793902-f665446b-9433-4b1f-a527-7e227c8f7ece.png)

But the `dbt_project.yml` file is in the root path of the git repository:

![image](https://user-images.githubusercontent.com/67712864/214794038-6805c896-ffc4-446a-9463-85d4c17675f5.png)

Am I doing something wrong here?
