### ISSUE TITLE
is there an ability to add support for passing `--vars` to the `dbt_command`? 

### ISSUE THREAD

**Issue by ari-stern** [mwhitaker/dbt-action#65]
i believe because of the need to have a colon the yaml isnt playing nicely, unless im missing something

example: 

```
    - name: dbt-deps
      uses: mwhitaker/dbt-action@v1.7.3
      with:
        dbt_command: "dbt deps --target pr --vars 'schema_id: 123' --profiles-dir ."
```

i consistently get an error like this no matter which syntax for vars i try: 

```
Error: Invalid value for '--vars': String ''schema_id:' is not valid YAML
```

I also tried some other fixes like prefacing the dbt_command string with a | or a > or escaping the quotes, but i think the problem is the colon

if you have any other suggested fixes for this that would be awesome!

**Comment by dylanvanw** [comment]
DBT commands that follow the correct format for YAML would be something like this:
```
dbt deps --target pr --vars "{'schema_id':'123'}" --profiles-dir .
```
or
```
dbt deps --target pr --vars "{'schema_id':123}" --profiles-dir .
```
As seen in: https://discourse.getdbt.com/t/confused-with-cli-vars-syntax/12355

It is possible that you will have to escape some of the quotes to have this working for github actions. Here are some examples: https://unix.stackexchange.com/questions/30903/how-to-escape-quotes-in-the-bash-shell

**Comment by dylanvanw** [comment]
Found that the issue is the space in the --vars yaml. The parser that reads the dbt_command string and translates it into argument tokens sees the space in the vars yaml as a separator between tokens.

More explanation on the whitespace being seen as a token: https://unix.stackexchange.com/questions/234755/command-line-processing-tokens-and-metacharacters

This issue is solved in other yaml configuration files by seperating the command from the argument list, like is done here: https://github.com/twpayne/chezmoi/discussions/1706
Example:
```
 dbt_command:
   - command: dbt
     args:
       - deps
       - --target
       - pr
       - --vars
       - 'schema_id: 123'
       - --profiles-dir
       - .
 ```
or this:
```
dbt_command:
   - command: dbt
     args: ['deps', '--target', 'pr', '--vars', 'schema_id: 123', '--profiles-dir', '.']
```

There might be another solution if I can find where the dbt_command is translated into what is executed in the docker container. The issue is that I cannot seem to find the part of the code in this repo that is responsible for using the provided value for dbt_command in the action. I can only find the input value here https://github.com/mwhitaker/dbt-action/blob/master/action.yml#L6

@mwhitaker could you point me in the right direction on how dbt_command value is executed in the docker container during the action execution?
