### ISSUE TITLE
Profiles.yml in the repo

### ISSUE THREAD

**Issue by moseleyi** [mwhitaker/dbt-action#66]
The recommendation here is to put these two in `profiles.yml`
```
pass: _password_
      user: _user_
```

But I realised that then when running dbt locally that profiles file will be taken first rather than my user files from `.dbt` folder?

How do you solve this problem?

**Comment by moseleyi** [comment]
I've tried using the following:

```


      - name: Set up dbt profiles directory
        run: |
          echo "$DBT_PROFILES" > ./profiles.yml

      - name: dbt-action
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt run --target=cicd --profiles-dir ."
        env:
          DBT_PROFILES: ${{ secrets.DBT_PROFILES }}
```

But I'm getting the following error:

```
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  The profiles.yml file at ./profiles.yml is empty
```
