### ISSUE TITLE
How to run dbt deps

### ISSUE THREAD

**Issue by moseleyi** [mwhitaker/dbt-action#69]
How to run `dbt deps` before the run/build?

**Comment by leo-schick** [comment]
add a second task into your GitHub workflow. E.g.:

``` yml
name: dbt run

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run dbt project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: dbt deps
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: dbt deps

      - name: dbt run
        uses: mwhitaker/dbt-action@v1.6.3
        with:
          dbt_command: dbt run
```
