### ISSUE TITLE
Use dbt-action with token (for eg DataBricks)

### ISSUE THREAD

**Issue by drernie** [mwhitaker/dbt-action#9]
DataBricks dbt profiles use a token instead of username/password

Is that possible today?

**Comment by mwhitaker** [comment]
Hi there,

Many thanks for writing. I'd be happy to work on adding support for databricks. Would you be able to send me a sample **profiles.yml** file so I can see the required fields.

**Comment by drernie** [comment]
Sure, here you go!
`default:
  target: dev
  outputs:
    dev:
      type: spark
      method: http
      schema: dev_ernest
      host: dbc-0b1dfbf6-3cc5.cloud.databricks.com
      port: 443
      token: HIDDEN
      cluster: 0505-153618-tours233
      connect_timeout: 30
      connect_retries: 15
      threads: 5
`

**Comment by mwhitaker** [comment]
OK let's try this since I don't yet use databricks myself.

1) In your profiles.yml, please change HIDDEN to \_token\_ so it should look like this:

```yml
default:
  target: dev
  outputs:
    dev:
      type: spark
      method: http
      schema: dev_ernest
      host: dbc-0b1dfbf6-3cc5.cloud.databricks.com
      port: 443
      token: _token_
      cluster: 0505-153618-tours233
      connect_timeout: 30
      connect_retries: 15
      threads: 5
```

2) Create a secret in your repo to hold the value of the databricks token, eg TOKEN

3) In your workflows file that uses this action, use this format:

```yml
    - name: dbt-action
      uses: mwhitaker/dbt-action@databricks
      with:
        dbt_command: "dbt run --profiles-dir ."
      env:
        DBT_TOKEN: ${{ secrets.TOKEN }}
```

Let me know if that works so I can add it to the main branch.

**Comment by drernie** [comment]
Hmm, didn't seem to work.

1. It complains about the missing spark adapter. I can try changing to http
2. It didn't seem to see the token.  I had to specify an "Environment" for the Secret - not sure that matters

```
/usr/bin/docker run --name a33c1ca867f13194f41ed88f6cb280670103b_b27b9b --label 8a33c1 --workdir /github/workspace --rm -e DBT_TOKEN -e INPUT_DBT_COMMAND -e INPUT_DBT_PROJECT_FOLDER -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/dbt_salesforce/dbt_salesforce":"/github/workspace" 8a33c1:ca867f13194f41ed88f6cb280670103b  "dbt run --profiles-dir ."
8
dbt project folder set as: "."
9
no token provided
10
saving console output in "./dbt_console_output.txt"
11
Running with dbt=0.19.0
12
Encountered an error while reading profiles:
13
  ERROR Runtime Error
14
  Credentials in profile "default", target "dev" invalid: Runtime Error
15
    Could not find adapter type spark!
16
```

**Comment by drernie** [comment]
Ah, it is already using the http adapter for spark.  It may need to be build into the environment. I wonder if it would help to run the dba-env command?

https://github.com/drernie/dbt_salesforce/pull/1/checks?check_run_id=2733635047

**Comment by drernie** [comment]
Does this seem to be the right way to add the secret?

<img width="964" alt="Screen Shot 2021-06-02 at 8 41 40 PM" src="https://user-images.githubusercontent.com/19791/120583372-f11a7400-c3e2-11eb-8c9c-cabd61958fc6.png">

**Comment by mwhitaker** [comment]
I don't think it's an issue with the secret - I just have a bad echo statement about the token missing that I'll take out. I think this has something to do with missing dependencies that databricks might need. Is there an example of a Dockerfile that works with dbt and databricks? Since I don't have any experience with databricks this is hard for me to test, so an option would be if you invite me to access your repo so I can try a few things to get this working.

**Comment by mwhitaker** [comment]
As a quick fix, I added dbt-spark to the Dockerfile. Can you try running the workflow again and see if it works?
Maybe also try with the simple `dbt --version` command:

```yml
- name: dbt-action
   uses: mwhitaker/dbt-action@databricks
   with:
      dbt_command: "dbt --version"
```
it should print out that the spark plugin is installed

**Comment by drernie** [comment]
Added you. Re-pushing
```
      - name: dbt-action
        uses: mwhitaker/dbt-action@databricks
        with:
          dbt_command: "dbt --version"
        env:
          DBT_TOKEN: ${{ secrets.TOKEN }}
      - name: dbt-action
        uses: mwhitaker/dbt-action@databricks
        with:
          dbt_command: "dbt debug --profiles-dir ."
        env:
          DBT_TOKEN: ${{ secrets.TOKEN }}
      - name: dbt-action
        uses: mwhitaker/dbt-action@databricks
        with:
          dbt_command: "dbt run --profiles-dir ."
        env:
          DBT_TOKEN: ${{ secrets.TOKEN }}
```
